import * as core from '@actions/core';
import * as github from '@actions/github';
import { exec } from '@actions/exec';

interface ReportData {
  total_commits: number;
  ai_commits: number;
  human_commits: number;
  ai_percent: number;
  by_agent: Record<string, number>;
  by_model: Record<string, number>;
  commits: Array<{
    hash: string;
    author: string;
    ai_agent: string | null;
    ai_model: string | null;
    ai_session: string | null;
    subject: string;
  }>;
  files: Array<{ path: string; ai_percent: number }>;
}

async function execAndCapture(cmd: string, args: string[]): Promise<string> {
  let stdout = '';
  await exec(cmd, args, {
    listeners: { stdout: (data: Buffer) => { stdout += data.toString(); } },
  });
  return stdout;
}

async function installSeshmark(): Promise<void> {
  await exec('bash', ['-c', 'curl -fsSL https://seshmark.github.io/seshmark/install.sh | bash || true']);
  // Force re-install the hook even if one already exists
  await exec('bash', ['-c', 'seshmark hook install --force 2>/dev/null || true']);
  core.addPath(`${process.env.HOME}/.local/bin`);
}

async function getReportData(baseSha: string, headSha: string): Promise<ReportData> {
  // Convert SHAs to dates (seshmark stats/query need dates, not SHAs)
  const baseDate = (await execAndCapture('git', ['log', '-1', '--format=%ci', baseSha])).trim();
  const headDate = (await execAndCapture('git', ['log', '-1', '--format=%ci', headSha])).trim();

  const statsOutput = await execAndCapture('seshmark', [
    'stats', '--since', baseDate, '--until', headDate, '--format', 'json'
  ]);
  const stats = JSON.parse(statsOutput);

  const queryOutput = await execAndCapture('seshmark', [
    'query', '--since', baseDate, '--until', headDate, '--format', 'json'
  ]);
  const commits = JSON.parse(queryOutput);

  return {
    total_commits: stats.total_commits || 0,
    ai_commits: stats.ai_commits || 0,
    human_commits: stats.human_commits || 0,
    ai_percent: stats.ai_percent || 0,
    by_agent: stats.by_agent || {},
    by_model: stats.by_model || {},
    commits: commits || [],
    files: stats.by_file || [],
  };
}

function formatReport(data: ReportData): string {
  const showModels = core.getInput('show-models') === 'true';
  const showSessions = core.getInput('show-sessions') === 'true';

  let md = `## 🤖 Seshmark AI Report\n\n`;
  md += `| Metric | Value |\n|--------|-------|\n`;
  md += `| **Total Commits** | ${data.total_commits} |\n`;
  md += `| **AI Commits** | ${data.ai_commits} (${data.ai_percent.toFixed(1)}%) |\n`;
  md += `| **Human Commits** | ${data.human_commits} |\n`;

  if (Object.keys(data.by_agent).length > 0) {
    const agents = Object.entries(data.by_agent).map(([k, v]) => `${k} (${v})`).join(', ');
    md += `| **Agents Used** | ${agents} |\n`;
  }
  if (showModels && Object.keys(data.by_model).length > 0) {
    md += `| **Models** | ${Object.keys(data.by_model).join(', ')} |\n`;
  }
  md += '\n';

  if (data.commits.length > 0) {
    md += `### Commits in this PR\n\n| Commit | Author | Agent |`;
    if (showModels) md += ` Model |`;
    if (showSessions) md += ` Session |`;
    md += `\n|--------|--------|-------|`;
    if (showModels) md += `-------|`;
    if (showSessions) md += `---------|`;
    md += '\n';

    for (const c of data.commits) {
      md += `| ${c.hash.substring(0, 7)} | @${c.author} | ${c.ai_agent || 'human'} |`;
      if (showModels) md += ` ${c.ai_model || '\u2014'} |`;
      if (showSessions) md += ` ${c.ai_session ? c.ai_session.substring(0, 20) + '...' : '\u2014'} |`;
      md += '\n';
    }
    md += '\n';
  }

  const aiFiles = data.files.filter((f: any) => f.ai_percent > 0).slice(0, 10);
  if (aiFiles.length > 0) {
    md += `### Files with AI Code\n\n| File | AI % |\n|------|------|\n`;
    for (const f of aiFiles) {
      md += `| ${f.path} | ${f.ai_percent.toFixed(0)}% |\n`;
    }
    md += '\n';
  }

  md += `---\n*Report generated by [Seshmark](https://seshmark.dev)*`;
  return md;
}

async function postComment(body: string): Promise<void> {
  const token = core.getInput('token');
  const octokit = github.getOctokit(token);
  const context = github.context;
  const prNumber = context.issue.number;

  // Find existing Seshmark comment to update
  const { data: comments } = await octokit.rest.issues.listComments({
    owner: context.repo.owner,
    repo: context.repo.repo,
    issue_number: prNumber,
  });

  const existing = comments.find(c =>
    c.user?.login === 'github-actions[bot]' &&
    c.body?.includes('Seshmark AI Report')
  );

  if (existing) {
    await octokit.rest.issues.updateComment({
      owner: context.repo.owner,
      repo: context.repo.repo,
      comment_id: existing.id,
      body,
    });
  } else {
    await octokit.rest.issues.createComment({
      owner: context.repo.owner,
      repo: context.repo.repo,
      issue_number: prNumber,
      body,
    });
  }
}

async function run(): Promise<void> {
  try {
    const pr = github.context.payload.pull_request;
    const baseSha = pr?.base?.sha;
    const headSha = pr?.head?.sha;

    if (!baseSha || !headSha) {
      core.setFailed('Could not determine PR commits');
      return;
    }

    await installSeshmark();
    const data = await getReportData(baseSha, headSha);
    const report = formatReport(data);
    await postComment(report);

    core.setOutput('ai-percent', data.ai_percent.toFixed(1));
    core.setOutput('agents-found', Object.keys(data.by_agent).join(', '));

    if (core.getInput('fail-on-unknown-agent') === 'true') {
      if (data.by_agent['unknown'] || data.by_agent['local']) {
        core.setFailed('PR contains commits from unapproved AI agents');
      }
    }
  } catch (error) {
    core.setFailed(error instanceof Error ? error.message : 'Unknown error');
  }
}

run();
